name: one_studio_core
description: Flutter package which contain the core file of one studio apps.
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  device_info: ^2.0.3
  flutter_screenutil: ^5.5.3+2
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  package_info_plus: ^3.0.2
  faker: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
